name: upload_example
on: push

env:
  IMAGE_REGISTRY: "ghcr.io"
  REGISTRY_USER: "${{ github.repository_owner }}"
  REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  IMAGE_REPO: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_NAME: "blob_example"
  DEBIAN_FRONTEND: noninteractive
  IMAGE_TAG: 0.0.1

jobs:
  build_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Login docker
        run: |
          echo ${{ env.REGISTRY_TOKEN }} | docker login ${{ env.IMAGE_REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin

      - name: docker upload
        run: |
          bash upload.sh ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} data.txt

      - name: docker download
        run: |
          mkdir empty_dir
          cd empty_dir
          bash ../download.sh ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} data.txt
          cat data.txt
          cd .. && rm -rf empty_dir

      - name: one-liner upload
        run: |
          echo one_liner > data.txt
          curl -fsSL https://raw.githubusercontent.com/ren15/blob/HEAD/upload.sh | bash -s ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} data.txt

      - name: one-liner download
        run: |
          mkdir empty_dir
          cd empty_dir
          curl -fsSL https://raw.githubusercontent.com/ren15/blob/HEAD/download.sh | bash -s ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} data.txt
          cat data.txt
          cd .. && rm -rf empty_dir


